[package]
name = "bnum"
version = "0.1.0"
authors = ["isaac-holt <isaac_holt@icloud.com>"]
edition = "2021"
license = "MIT OR Apache-2.0"
description = "Arbitrary precision, fixed size numeric types that behave the same as the primitive numeric types."
homepage = "https://crates.io/" # TODO: decide on name
documentation = "https://docs.rs/"
repository = "https://github.com/isaacholt100/"
readme = "README.md"
keywords = ["uint", "int", "bignum", "maths", "arbitrary"]
categories = ["numbers", "algorithms", "mathematics"]

[features]
default = ["u8_digit", "numtraits"]
u8_digit = []
serde = ["dep:serde", "serde-big-array"]
numtraits = ["num-integer", "num-traits"]

[dependencies]
num-integer = { version = "0.1.44", optional = true }
num-traits = { version = "0.2.14", optional = true }
serde = { version = "1.0.126", features = ["derive"], optional = true }
serde-big-array = { version = "0.3.2", features = ["const-generics"], optional = true }
rand = { version = "0.8.5", features = ["min_const_gen"], optional = true }

[dev-dependencies]
quickcheck = "1.0.3"
paste = "1.0.6"