[package]
name = "bnum_benchmarks"
version = "0.1.0"
authors = ["isaac-holt <isaac_holt@icloud.com>"]
edition = "2021"
license = "MIT OR Apache-2.0"

[dev-dependencies]
criterion = "0.3.6"
bnum = { path = "../" }

[[bench]]
name = "benchmark"
harness = false

[profile.release]
lto = true # enable link-time optimisation for faster runtime, but slower compile time
opt-level = 3 # maximum optimisation level for faster runtime, but slower compile time