name: Verify MSRV

on:
  push:
    branches: "**"
  pull_request:
    branches: "**"

env:
  CARGO_TERM_COLOR: always

jobs:
  cargo-msrv:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust
        run: rustup update nightly
      - name: Set nightly as default
        run: rustup default nightly
      - name: Install cargo-binstall
        uses: cargo-bins/cargo-binstall@v1
      - name: Install cargo-msrv
        run: cargo binstall cargo-msrv --no-confirm
      - name: verify MSRV
        run: cargo msrv verify