name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Update toolchain to nightly
      run: rustup install nightly
    - name: Set nightly as default
      run: rustup default nightly
    - name: Build
      run: cargo build --all-features --verbose
    - name: Run tests
      run: sh scripts/run_all_tests.sh
    - name: Run doc tests
      run: cargo test --all-features --doc && cargo test --doc
